-- AlterTable
ALTER TABLE "property" ADD COLUMN     "additional" JSONB,
ALTER COLUMN "entry_yeild" SET DATA TYPE TEXT,
ALTER COLUMN "irr" SET DATA TYPE TEXT,
ALTER COLUMN "multiplier" SET DATA TYPE TEXT,
ALTER COLUMN "floorplan" DROP NOT NULL,
ALTER COLUMN "tenant_details" DROP NOT NULL,
ALTER COLUMN "images" DROP NOT NULL,
ALTER COLUMN "images" SET DATA TYPE TEXT,
ALTER COLUMN "tables" DROP NOT NULL;
