# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fidelx
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: portal
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
